# Generated by Django 5.1.3 on 2024-11-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='aguardando', max_length=15),
        ),
    ]
