# Generated by Django 4.2.16 on 2024-11-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_agendamento_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='data_agendamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
